protected/models/Clientes.php
<?php

/**
 * This is the model class for table "clientes".
 *
 * The followings are the available columns in table 'clientes':
 * @property integer $id
 * @property string $direccion
 * @property integer $usuarios_id
 * @property integer $comunas_id
 * @property string $rut
 */
class Clientes extends CActiveRecord
{
    public $comuna;
    public $region;
    public $user;
    public $nombre;
    
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Clientes the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'clientes';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('direccion, usuarios_id, comunas_id', 'required'),
			array('usuarios_id, comunas_id', 'numerical', 'integerOnly'=>true),
                        array('rut', 'esRut'),
			array('direccion', 'length', 'max'=>200),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, direccion,region, rut,user,nombre,comuna,usuarios_id, comunas_id', 'safe', 'on'=>'search'),
		);
	}
        
        public function esRut($attribute,$params)
        {
            if($this->$attribute != ""){
                $rut = str_replace (".", "", $this->$attribute);
                $arr = explode("-", $rut);
                if(count($arr)!=2){
                    $this->addError($attribute, 'Ingrese un RUT válido, con guión y sin puntos.');
                }
                else{
                    $dv = $arr[1];
                    if(Tools::dv($arr[0])!=$dv){
                         $this->addError($attribute, 'RUT inválido');
                    }
                }
            }
        }

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
                    'usuarios' => array(self::BELONGS_TO, 'Usuarios', 'usuarios_id'),
                    'comunas' => array(self::BELONGS_TO, 'Comunas', 'comunas_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'direccion' => 'Direccion',
			'usuarios_id' => 'Usuarios',
                        'user'=>'Email',
                        'nombre'=>'Nombre',
			'comunas_id' => 'Comunas',
                        'region'=>'Región',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
                //$criteria->with = array('comunas','usuarios');
                $criteria->join = " join comunas on comunas.id = t.comunas_id "
                        . "         join usuarios on usuarios.id = t.usuarios_id "
                        . "         join regiones on regiones.id = comunas.regiones_id ";
		$criteria->compare('id',$this->id);
		$criteria->compare('direccion',$this->direccion,true);
		$criteria->compare('usuarios_id',$this->usuarios_id);
                $criteria->compare('rut',$this->rut,true);
		$criteria->compare('comunas.nombre',$this->comuna,true);
                $criteria->compare('regiones.nombre',$this->region,true);
                $criteria->compare('usuarios.user',$this->user,true);
                $criteria->compare('usuarios.nombre',$this->nombre,true);

		return new CActiveDataProvider($this, array(
                    'criteria'=>$criteria,
                    'sort'=>array(
                        'attributes'=>array(
                            'user'=>array(
                                'asc'=>'usuarios.user',
                                'desc'=>'usuarios.user DESC',
                            ),
                            'nombre'=>array(
                                'asc'=>'usuarios.nombre',
                                'desc'=>'usuarios.nombre DESC',
                            ),
                            'comuna'=>array(
                                'asc'=>'comunas.nombre',
                                'desc'=>'comunas.nombre DESC',
                            ),
                            'region'=>array(
                                'asc'=>'regiones.nombre',
                                'desc'=>'regiones.nombre DESC',
                            ),
                            '*',
                        ),
                    ),
		));
	}
}

protected/controllers/ClientesController.php
<?php

class ClientesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','create','update','admin','delete','exportar'),
				'roles'=>array('administrador'),
			),
                        array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','actualiza','cambiarClave','misPedidos','pedidoOK'),
				'roles'=>array('cliente'),
			),
                        array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('recupera'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Clientes;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Clientes']))
		{
			$model->attributes=$_POST['Clientes'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Clientes']))
		{
			$model->attributes=$_POST['Clientes'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

        
        public function actionCambiarClave()
	{
		$form = new CambiarClaveForm();
		if (isset(Yii::app()->user->id))
		{
			if(isset($_POST['CambiarClaveForm']))
			{
				$form->attributes = $_POST['CambiarClaveForm'];
				if($form->validate())
				{
					$new_password = Usuarios::model()->findByPk(Yii::app()->user->id);
					if($new_password->clave != sha1($form->clave))
					{
						$form->addError('clave', "clave incorrecta");
					}
					else
					{
						if($form->nueva == $form->repita){
							$new_password->clave = sha1($form->nueva);
							if($new_password->save())
							{
								Yii::app()->user->setFlash('profileMessage',
										"Clave cambiada correctamente.");
							}
							else
							{
								Yii::app()->user->setFlash('profileMessage',
										"No se pudo cambiar la clave, inténtelo de nuevo más tarde.");
							}
							$this->refresh();
						}
						else{
							$form->addError('nueva', "claves nuevas no coinciden");
							$form->addError('repita', "claves nuevas no coinciden");
						}
	
					}
				}
			}
			$this->render('cambiarClave',array('model'=>$form));
		}
	}

        public function actionRecupera()
	{
		$form = new CambiarClaveForm();
		if(isset($_POST['CambiarClaveForm']))
                {
                        $form->attributes = $_POST['CambiarClaveForm'];
                        $user = CHtml::encode($_GET['usuario']);
                        $hash = CHtml::encode($_GET['hash']);
                        if($hash == ""){
                            Yii::app()->user->setFlash('error',"ERROR: HASH INCORRECTO.");
                            $this->refresh();
                            Yii::app()->end;
                        }
                        
                        $form->clave = "1234";
                        if($form->validate())
                        {
                            if($form->nueva == $form->repita){
                                $user = Usuarios::model()->findByAttributes(array('user'=>$user,'hash'=>$hash));
                                if($user != null){
                                    $user->clave = sha1($form->nueva);
                                    $user->hash = "";
                                    if($user->save()){
                                        Yii::app()->user->setFlash('ok',"Clave cambiada correctamente.");
                                    }
                                    else{
                                        Yii::app()->user->setFlash('error',"No se pudo cambiar la clave, inténtelo de nuevo más tarde.");
                                    }
                                    $this->refresh();
                                    Yii::app()->end;
                                }
                                else{
                                    Yii::app()->user->setFlash('error',"ERROR: USUARIO Y HASH NO COINCIDEN.");
                                    $this->refresh();
                                    Yii::app()->end;
                                }
                            }
                            else{
                                Yii::app()->user->setFlash('error',"ERROR: CLAVES NO COINCIDEN.");
                                $this->refresh();
                                Yii::app()->end;
                            }					
                        }else{
                            Yii::app()->user->setFlash('error',"ERROR EN EL FORMULARIO:".CHtml::errorSummary($form));
                            $this->refresh();
                            Yii::app()->end;
                        }
                            
                }
                $this->render('recupera',array('model'=>$form));

	}
        
	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
            $this->render('index');
	}
        
        
        public function actionActualiza(){
            $model=new RegistrateForm;

            $comuna_nombre = "";
            if(isset($_POST['RegistrateForm']))
            {
                $model->attributes=$_POST['RegistrateForm'];
                $comuna = Comunas::model()->findByPk($model->comuna_id);
                $comuna_nombre = $comuna->nombre;
                $model->password = "123";
                $model->repite_password = "123";
                if($model->validate()){
                    $usuario = Usuarios::model()->findByAttributes(array('user'=>$model->username));
                    $usuario->nombre = $model->nombre;
                    if($usuario->save()){
                        $cliente = Clientes::model()->findByAttributes(array('usuarios_id'=>$usuario->id));
                        $cliente->comunas_id = $model->comuna_id;
                        $cliente->direccion = $model->direccion;
                        $cliente->rut = $model->rut;
                        if($cliente->save()){
                            Yii::app()->user->setFlash('success',"Sus datos fueron correctamente cambiados.");
                            $this->refresh();                    
                        }
                        else{
                            Yii::app()->user->setFlash('error',"Error: sus datos no fueron actualizados, reintente.");
                            $this->refresh();
                        }
                    }
                    else{
                        Yii::app()->user->setFlash('error',CHtml::errorSummary($usuario));
                        $this->refresh();
                    }
                }
                else{
                    Yii::app()->user->setFlash('error',CHtml::errorSummary($model));
                    $this->refresh();
                }

            }else{
                $usuario_id = Yii::app()->user->id;
                $usuario = Usuarios::model()->findByPk($usuario_id);
                $cliente = Clientes::model()->findByAttributes(array('usuarios_id'=>$usuario_id));
                $comuna_id = $cliente->comunas_id;
                $comuna = Comunas::model()->findByPk($comuna_id);
                $region = $comuna->regiones;
                $region_id = $region->id;
                
                $model->comuna_id = $comuna_id;
                $model->rut = $cliente->rut;
                $model->region_id = $region_id;
                $model->direccion = $cliente->direccion;
                $model->nombre = $usuario->nombre;
                $model->username = $usuario->user;
                
                $comuna_nombre = $comuna->nombre;
            }
            // display the registrate form
            $this->render('cambiaDatos',array('model'=>$model,'comuna_nombre'=>$comuna_nombre));
        }

        public function actionMisPedidos(){
        }

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Clientes('search');

protected/views/clientes/_form.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'clientes-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'nombre'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'direccion'); ?>
		<?php echo $form->textField($model,'direccion',array('size'=>60,'maxlength'=>200)); ?>
		<?php echo $form->error($model,'direccion'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'ciudades_id'); ?>
		<?php 
			echo $form->dropDownList(
				$model,
				'ciudades_id',
				CHtml::listData(Ciudades::model()->findAll(), 'id', 'nombre'),
				array('prompt'=>'Seleccione una Ciudad',)
			);
		?>
		<?php echo $form->error($model,'ciudades_id'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Crear' : 'Grabar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/clientes/_search.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'direccion'); ?>
		<?php echo $form->textField($model,'direccion',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'ciudades_id'); ?>
		<?php 
			echo $form->dropDownList(
				$model,
				'ciudades_id',
				CHtml::listData(Ciudades::model()->findAll(), 'id', 'nombre'),
				array('prompt'=>'Seleccione una Ciudad',)
			);
		?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Buscar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/clientes/_view.php
<?php
/* @var $this ClientesController */
/* @var $data Clientes */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombre')); ?>:</b>
	<?php echo CHtml::encode($data->nombre); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('direccion')); ?>:</b>
	<?php echo CHtml::encode($data->direccion); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('ciudades_id')); ?>:</b>
	<?php echo CHtml::encode($data->ciudades_id); ?>
	<br />


</div>

protected/views/clientes/admin.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */

$this->menu=array(
	array('label'=>'Listar Clientes', 'url'=>array('index')),
	array('label'=>'Crear Clientes', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#clientes-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Administrar Clientes</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'clientes-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
            'rut',
            array('name'=>'user','value'=>'$data->usuarios->user'),
            array('name'=>'nombre','value'=>'$data->usuarios->nombre'),
            'direccion',
            array('name'=>'comuna','value'=>'$data->comunas->nombre'),
            array('name'=>'region','value'=>'$data->comunas->regiones->nombre'),
	),
)); ?>

protected/views/clientes/cambiaDatos.php
<div class="form magenta mag_center">
<?php $form=$this->beginWidget('CActiveForm', array(
        'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
            'validateOnSubmit'=>true,
	),
)); ?>
    <script>
    $(document).ready(function(e){
        
        $("#RegistrateForm_region_id").change(function(e){
            $("#comuna_id").html("<option value=''>Seleccione una Comuna</option>");
        });
        
        $("#comuna_id").html("<option value='<?php echo $model->comuna_id?>'><?php echo $comuna_nombre?></option>");
                
        $('.btn_aceptar').click(function(e){
            $('#login-form').submit();
            //e.preventDefault();
        });
    });
    </script>
    <br/>
<?php if(Yii::app()->user->hasFlash('success')):?>
    <div class="flash-success">
        <?php echo Yii::app()->user->getFlash('success'); ?>
    </div>
<?php endif; ?>
<?php if(Yii::app()->user->hasFlash('error')):?>
    <div class="flash-error">
        <?php echo Yii::app()->user->getFlash('error'); ?>
    </div>
<?php endif; ?>
    <div class="mag_left">
        <p class="titulo_reg">Actualiza tus datos</p>
        <div class="cuadro">
            <div class="row">
                <?php echo $form->labelEx($model,'username'); ?>
                <?php echo $form->textField($model,'username',array('placeholder'=>'correo@correo.com','readonly'=>'readonly')); ?>
                <?php echo $form->error($model,'username'); ?><div class="error_usuario"></div>
            </div>
            
            <div class="row">
                <?php echo $form->labelEx($model,'rut'); ?>
                <?php echo $form->textField($model,'rut',array('placeholder'=>'12345678-9')); ?>
                <?php echo $form->error($model,'rut'); ?><div class="error_usuario"></div>
            </div>
            
            <div class="row">
                <?php echo $form->labelEx($model,'nombre'); ?>
                <?php echo $form->textField($model,'nombre',array('placeholder'=>'Nombre Apellido')); ?>
                <?php echo $form->error($model,'nombre'); ?>
            </div>
            <div class="row">
                <?php echo $form->labelEx($model,'direccion'); ?>
                <?php echo $form->textField($model,'direccion',array('placeholder'=>'Calle N° Población/Villa')); ?>
                <?php echo $form->error($model,'direccion'); ?>
            </div>
            
        </div>
        <div class="cuadro">
            <div class="row">
                <?php echo $form->labelEx($model,'region_id'); ?>
                <?php echo $form->dropDownList($model,'region_id', CHtml::listData(Regiones::model()->listar(), 'id', 'nombre'),
                        array(
                            'ajax' => array(
                                'type'=>'POST', //request type
                                'url'=>CController::createUrl('//regiones/llenaComuna'), 
                                'update'=>'#comuna_id', 
                            ),
                            'prompt'=>'Seleccione una Región')); ?>
                <?php echo $form->error($model,'region_id'); ?>
            </div>

            <div class="row">
                <?php echo $form->labelEx($model,'comuna_id'); ?>
                <?php echo $form->dropDownList($model,'comuna_id',array(),
                        array(
                            'prompt'=>'Seleccione una Comuna',
                            'id'=>'comuna_id',
                        )
                    ); ?>
                <?php echo $form->error($model,'comuna_id'); ?>
            </div>


        </div>
        
        <div class="row buttons">
            <div class="boton_comprar_chico btn_aceptar">Guardar Cambios</div>
        </div>

    </div>    
<?php $this->endWidget(); ?>
</div><!-- form -->

protected/views/clientes/cambiarClave.php
<?php if(Yii::app()->user->hasFlash('profileMessage')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('profileMessage'); ?>
</div>

<?php else: ?>

<div class="form_cambio">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Campos con <span class="required">*</span> son requeridos.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'clave'); ?>
		<?php echo $form->passwordField($model,'clave'); ?>
		<?php echo $form->error($model,'clave'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nueva'); ?>
		<?php echo $form->passwordField($model,'nueva'); ?>
		<?php echo $form->error($model,'nueva'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'repita'); ?>
		<?php echo $form->passwordField($model,'repita'); ?>
		<?php echo $form->error($model,'repita'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Cambiar Clave',array('class'=>'btn')); ?>
	</div>

<?php $this->endWidget(); 
endif;?>

</div><!-- form -->

protected/views/clientes/create.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */

$this->breadcrumbs=array(
	'Clientes'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'Listar Clientes', 'url'=>array('index')),
	array('label'=>'Administrar Clientes', 'url'=>array('admin')),
);
?>

<h1>Crear Clientes</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/clientes/index.php
<div class="menu-abajo center">
    <h4>Mi cuenta</h4>
<?php

echo CHtml::link("Actualiza tus datos",CController::createUrl("/clientes/actualiza"),array('class'=>'link_cuenta'))."<br/>";
echo CHtml::link("Cambia tu clave",CController::createUrl("/clientes/cambiarClave"),array('class'=>'link_cuenta'))."<br/>";
?>
</div><!-- form -->

protected/views/clientes/recupera.php
<?php
if(Yii::app()->user->hasFlash('error')):
?>
    <div class="alert-error">
        <?php echo Yii::app()->user->getFlash('error');?>
    </div>    
<?php   
endif;
if(Yii::app()->user->hasFlash('ok')):
?>
    <div class="alert-success">
        <?php echo Yii::app()->user->getFlash('ok');?>
    </div>    
<?php   
endif;
?>

<div class="form_cambio">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Campos con <span class="required">*</span> son requeridos.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'nueva'); ?>
		<?php echo $form->passwordField($model,'nueva'); ?>
		<?php echo $form->error($model,'nueva'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'repita'); ?>
		<?php echo $form->passwordField($model,'repita'); ?>
		<?php echo $form->error($model,'repita'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Cambiar Clave',array('class'=>'btn')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/clientes/update.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */


$this->menu=array(
	array('label'=>'Listar Clientes', 'url'=>array('index')),
	array('label'=>'Crear Clientes', 'url'=>array('create')),
	array('label'=>'Ver Clientes', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Administrar Clientes', 'url'=>array('admin')),
);
?>

<h1>Editar Clientes <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/clientes/view.php
<?php
/* @var $this ClientesController */
/* @var $model Clientes */


$this->menu=array(
	array('label'=>'List Clientes', 'url'=>array('index')),
	array('label'=>'Create Clientes', 'url'=>array('create')),
	array('label'=>'Update Clientes', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Clientes', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Clientes', 'url'=>array('admin')),
);
?>

<h1>Ver Clientes #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'nombre',
		'email',
		'direccion',
		array('name'=>'ciudad','value'=>$model->ciudades->nombre),
	),
)); ?>